apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.service.group: trex
    kompose.volume.type: configMap
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-trex-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-trex-2
    app.kubernetes.io/part-of: rh-trex-2
    io.kompose.service: trex
  name: rh-trex-2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rh-trex-2
      io.kompose.service: trex
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.service.group: trex
        kompose.volume.type: configMap
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rh-trex-2
        io.kompose.network/rh-trex-default: "true"
        io.kompose.service: trex
    spec:
      containers:
      - args:
        - "/rh-trex/trex migrate\n/rh-trex/trex serve --api-server-bindaddress=0.0.0.0:8000
          \     \n"
        command:
        - sh
        - -c
        image: quay.io/redhat-user-workloads/ysubrama-tenant/rh-trex-2/rh-trex-2@sha256:235ada024fa4c7e2010d0aa2676f769649ccaa9a0f53f9ac89f956ee856ad6a6
        name: trex
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
        volumeMounts:
        - mountPath: /rh-trex/secrets
          name: trex-cm0
      initContainers:
      - command:
        - /rh-trex/trex
        - migrate
        image: quay.io/yogananth_subramanian/trex
        name: trex-init
        resources: {}
        volumeMounts:
        - mountPath: /rh-trex/secrets
          name: trex-cm0
      restartPolicy: Always
      volumes:
      - configMap:
          name: trex-cm0
        name: trex-cm0
status: {}
