apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.service.group: trex
    kompose.volume.type: configMap
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-trex-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-trex-2
    app.kubernetes.io/part-of: rh-trex-2
    io.kompose.service: trex
  name: rh-trex-2
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: rh-trex-2
    io.kompose.service: trex
status:
  loadBalancer: {}
