apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rh-trex-2
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ysubrama-tenant/rh-trex-2/rh-trex-2@sha256:63f75f7ede84a8b1f6aa7cf261e10aa57800d0908583f841513271abd6d04bff
        name: trex
        resources: {}
status: {}
