apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-trex-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-trex-2
    app.kubernetes.io/part-of: rh-trex-2
  name: rh-trex-2unob
spec:
  path: /
  port:
    targetPort: 8000
  to:
    kind: Service
    name: rh-trex-2
    weight: null
status: {}
